import ArkWallet.Security.ThreatGuard

open ArkWallet.Security

/-!
  AUTO-GENERATED by `tsx scripts/fv-extract.ts` — do not edit by hand.
-/

namespace ArkWallet.FvFixtures

def canonicalVersion : String := "v2"

def signingPath0_pathname : String := "/api/wallet/address"

def signingPath0_search : String := "?rotate=1&foo=2"

def signingPath0_expected : String := "/api/wallet/address?foo=2&rotate=1"

def signingPath1_pathname : String := "/api/wallet/address"

def signingPath1_search : String := "?foo=2&rotate=1"

def signingPath1_expected : String := "/api/wallet/address?foo=2&rotate=1"

def signingPath2_pathname : String := "/api/wallet/address"

def signingPath2_search : String := ""

def signingPath2_expected : String := "/api/wallet/address"

def signingPath3_pathname : String := "/api/wallet/address"

def signingPath3_search : String := "?rotate=1"

def signingPath3_expected : String := "/api/wallet/address?rotate=1"

def hashBody0_input : String := "{\"a\":1}"

def hashBody0_expected : String := "AVq9f1zFei3ZS3WQ8ErYCEJzkF7jPsXOvq5iJ2qX+GI="

def hashBody1_input : String := "{\"a\":2}"

def hashBody1_expected : String := "foBZ9JVYn82YEjLMEdALANo4AsAdaI+hzx9r7W5bszw="

def canonical0_method : String := "post"

def canonical0_path : String := "/api/wallet/send"

def canonical0_timestamp : String := "1"

def canonical0_nonce : String := "n"

def canonical0_bodyHash : String := "h"

def canonical0_text_expected : String := "v2\nPOST\n/api/wallet/send\n1\nn\nh"

def nonce0_input : String := "a1b2c3d4-e5f6-4789-a012-3456789abcde"

def nonce0_valid_expected : Bool := true

def nonce1_input : String := "not-a-uuid"

def nonce1_valid_expected : Bool := false

def nonce2_input : String := ""

def nonce2_valid_expected : Bool := false

def loopbackHost0_input : String := "127.0.0.1"

def loopbackHost0_expected : Bool := true

def loopbackHost1_input : String := "192.168.1.1"

def loopbackHost1_expected : Bool := false

def loopbackHost2_input : String := "LOCALHOST"

def loopbackHost2_expected : Bool := true

def hostHeader0_input : Option String := some "127.0.0.1:3000"
def hostHeader0_expected : Option String := some "127.0.0.1"

def hostHeader1_input : Option String := none
def hostHeader1_expected : Option String := none

def challengeMsg0_challenge : String := "abc123"

def challengeMsg0_register_expected : String := "wallet-register\nabc123"

def challengeMsg0_setup_expected : String := "wallet-webauthn-setup\nabc123"

def timestamp0_now : Nat := 1700000000000
def timestamp0_ts : Nat := 1700000000000
def timestamp0_expected : Bool := true

def timestamp1_now : Nat := 1700000000000
def timestamp1_ts : Nat := 1700000300000
def timestamp1_expected : Bool := true

def timestamp2_now : Nat := 1700000000000
def timestamp2_ts : Nat := 1700000300001
def timestamp2_expected : Bool := false

def pendingOp0_pathname : String := "/api/wallet/send"

def pendingOp0_search : String := ""

def pendingOp0_expected : Option String := some "send"

def pendingOp1_pathname : String := "/api/wallet/send/estimate"

def pendingOp1_search : String := ""

def pendingOp1_expected : Option String := some "send"

def pendingOp2_pathname : String := "/api/wallet/address"

def pendingOp2_search : String := "?rotate=1"

def pendingOp2_expected : Option String := some "rotateAddress"

def pendingOp3_pathname : String := "/api/wallet/balance"

def pendingOp3_search : String := ""

def pendingOp3_expected : Option String := none

def pageCsp0_nonce : String := "fv-nonce-abc"

def pageCsp0_text : String := "default-src 'self'; script-src 'self' 'nonce-fv-nonce-abc' 'strict-dynamic'; script-src-attr 'none'; script-src-elem 'self' 'nonce-fv-nonce-abc' 'strict-dynamic'; style-src 'self' 'unsafe-inline'; img-src 'self' data:; connect-src 'self'; font-src 'self'; object-src 'none'; form-action 'self'; frame-src 'none'; frame-ancestors 'none'; child-src 'none'; worker-src 'none'; manifest-src 'self'; media-src 'none'; base-uri 'self'; trusted-types ark-wallet; require-trusted-types-for 'script'"

def pageCsp0_hardened_expected : Bool := true

def apiCsp0_text : String := "default-src 'none'; script-src 'none'; script-src-attr 'none'; style-src 'none'; object-src 'none'; frame-ancestors 'none'; base-uri 'none'; form-action 'none'"

def apiCsp0_hardened_expected : Bool := true

def trustedUrl0_origin : String := "http://127.0.0.1:3000"

def trustedUrl0_url : String := "/_next/static/chunk.js"

def trustedUrl0_allowed_expected : Bool := true

def trustedUrl1_origin : String := "http://127.0.0.1:3000"

def trustedUrl1_url : String := "http://127.0.0.1:3000/_next/static/chunk.js"

def trustedUrl1_allowed_expected : Bool := true

def trustedUrl2_origin : String := "http://127.0.0.1:3000"

def trustedUrl2_url : String := "https://evil.example/x.js"

def trustedUrl2_allowed_expected : Bool := false

def signing0_embedded : Bool := false
def signing0_permitted_expected : Bool := true

def signing1_embedded : Bool := true
def signing1_permitted_expected : Bool := false

def threat0_signal : ThreatSignal := .blur
def threat0_cfg : ThreatGuardConfig := { lockOnBlur := true, lockOnHide := true }
def threat0_lock_expected : Bool := true

def threat1_signal : ThreatSignal := .blur
def threat1_cfg : ThreatGuardConfig := { lockOnBlur := false, lockOnHide := true }
def threat1_lock_expected : Bool := false

def threat2_signal : ThreatSignal := .embedded
def threat2_cfg : ThreatGuardConfig := { lockOnBlur := false, lockOnHide := false }
def threat2_lock_expected : Bool := true

def reg0_embedded : Bool := true
def reg0_secure : Bool := true
def reg0_lock_expected : Bool := true

def reg1_embedded : Bool := false
def reg1_secure : Bool := false
def reg1_lock_expected : Bool := true

end ArkWallet.FvFixtures
