#!/usr/bin/env node
/**
 * Extract pure-function fixtures for Lean refinement tests.
 * Writes lean/ArkWallet/FvFixtures.lean
 *
 * Usage: node scripts/fv-extract.mjs
 */
import { createHash } from "node:crypto";
import { mkdirSync, writeFileSync } from "node:fs";
import { dirname, join } from "node:path";
import { fileURLToPath } from "node:url";

const __dirname = dirname(fileURLToPath(import.meta.url));
const root = join(__dirname, "..");

export const CANONICAL_VERSION = "v2";
const MAX_CLOCK_SKEW_MS = 5 * 60 * 1000;

export function hashBody(body) {
  const digest = createHash("sha256").update(body, "utf8").digest();
  return digest.toString("base64");
}

export function signingPath(pathname, search) {
  if (!search || search === "?") return pathname;
  const raw = search.startsWith("?") ? search.slice(1) : search;
  const params = new URLSearchParams(raw);
  const sorted = [...params.entries()].sort(([a], [b]) => a.localeCompare(b));
  const qs = new URLSearchParams(sorted).toString();
  return qs ? `${pathname}?${qs}` : pathname;
}

export function canonicalRequest(parts) {
  const payload = [
    CANONICAL_VERSION,
    parts.method.toUpperCase(),
    parts.path,
    parts.timestamp,
    parts.nonce,
    parts.bodyHash,
  ].join("\n");
  return Buffer.from(payload, "utf8");
}

const NONCE_UUID_RE =
  /^[0-9a-f]{8}-[0-9a-f]{4}-[1-5][0-9a-f]{3}-[89ab][0-9a-f]{3}-[0-9a-f]{12}$/i;

export function isValidNonceUuid(nonce) {
  return NONCE_UUID_RE.test(nonce);
}

export function challengeMessage(challenge) {
  return `wallet-register\n${challenge}`;
}

export function webauthnSetupMessage(challenge) {
  return `wallet-webauthn-setup\n${challenge}`;
}

export function isTimestampValid(timestampMs, now = 1_700_000_000_000) {
  return Math.abs(now - timestampMs) <= MAX_CLOCK_SKEW_MS;
}

export const LOOPBACK_HOSTS = ["127.0.0.1", "localhost", "::1", "[::1]"];

export function isLoopbackHostname(hostname) {
  return LOOPBACK_HOSTS.includes(hostname.toLowerCase());
}

export function hostFromRequestHeader(hostHeader) {
  if (!hostHeader) return null;
  return hostHeader.split(":")[0]?.toLowerCase() ?? null;
}

export function isLoopbackUrl(urlString) {
  try {
    return isLoopbackHostname(new URL(urlString).hostname);
  } catch {
    return false;
  }
}

export function pendingOpTypeForPath(pathname, search = "") {
  if (pathname.endsWith("/send/estimate")) return "send";
  if (pathname.endsWith("/send")) return "send";
  if (pathname.endsWith("/refresh")) return "refresh";
  if (pathname.includes("/address") && search.includes("rotate=1")) {
    return "rotateAddress";
  }
  return null;
}

function leanStr(s) {
  return JSON.stringify(s);
}

function emitFixtures(data) {
  const lines = [
    "/-!",
    "  AUTO-GENERATED by `node scripts/fv-extract.mjs` — do not edit by hand.",
    "-/",
    "",
    "namespace ArkWallet.FvFixtures",
    "",
    `def canonicalVersion : String := ${leanStr(data.version)}`,
    "",
  ];

  const emit = (name, value) => {
    if (typeof value === "boolean") {
      lines.push(`def ${name} : Bool := ${value ? "true" : "false"}`);
    } else {
      lines.push(`def ${name} : String := ${leanStr(value)}`);
    }
    lines.push("");
  };

  data.signingPath.forEach((c, i) => {
    emit(`signingPath${i}_pathname`, c.pathname);
    emit(`signingPath${i}_search`, c.search);
    emit(`signingPath${i}_expected`, c.result);
  });

  data.hashBody.forEach((c, i) => {
    emit(`hashBody${i}_input`, c.body);
    emit(`hashBody${i}_expected`, c.result);
  });

  data.canonical.forEach((c, i) => {
    emit(`canonical${i}_method`, c.parts.method);
    emit(`canonical${i}_path`, c.parts.path);
    emit(`canonical${i}_timestamp`, c.parts.timestamp);
    emit(`canonical${i}_nonce`, c.parts.nonce);
    emit(`canonical${i}_bodyHash`, c.parts.bodyHash);
    emit(`canonical${i}_text_expected`, c.text);
  });

  data.nonce.forEach((n, i) => {
    emit(`nonce${i}_input`, n.input);
    lines.push(`def nonce${i}_valid_expected : Bool := ${n.valid ? "true" : "false"}`);
    lines.push("");
  });

  data.loopback.forEach((c, i) => {
    emit(`loopbackHost${i}_input`, c.input);
    lines.push(`def loopbackHost${i}_expected : Bool := ${c.expected ? "true" : "false"}`);
    lines.push("");
  });

  data.hostHeader.forEach((c, i) => {
    if (c.input === null) {
      lines.push(`def hostHeader${i}_input : Option String := none`);
    } else {
      lines.push(`def hostHeader${i}_input : Option String := some ${leanStr(c.input)}`);
    }
    if (c.expected === null) {
      lines.push(`def hostHeader${i}_expected : Option String := none`);
    } else {
      lines.push(`def hostHeader${i}_expected : Option String := some ${leanStr(c.expected)}`);
    }
    lines.push("");
  });

  data.challengeMsg.forEach((c, i) => {
    emit(`challengeMsg${i}_challenge`, c.challenge);
    emit(`challengeMsg${i}_register_expected`, c.register);
    emit(`challengeMsg${i}_setup_expected`, c.setup);
  });

  data.timestamp.forEach((c, i) => {
    lines.push(`def timestamp${i}_now : Nat := ${c.now}`);
    lines.push(`def timestamp${i}_ts : Nat := ${c.ts}`);
    lines.push(`def timestamp${i}_expected : Bool := ${c.expected ? "true" : "false"}`);
    lines.push("");
  });

  data.pendingOp.forEach((c, i) => {
    emit(`pendingOp${i}_pathname`, c.pathname);
    emit(`pendingOp${i}_search`, c.search);
    if (c.expected === null) {
      lines.push(`def pendingOp${i}_expected : Option String := none`);
    } else {
      lines.push(`def pendingOp${i}_expected : Option String := some ${leanStr(c.expected)}`);
    }
    lines.push("");
  });

  lines.push("end ArkWallet.FvFixtures");
  lines.push("");
  return lines.join("\n");
}

const NOW = 1_700_000_000_000;

const data = {
  version: CANONICAL_VERSION,
  signingPath: [
    { pathname: "/api/wallet/address", search: "?rotate=1&foo=2" },
    { pathname: "/api/wallet/address", search: "?foo=2&rotate=1" },
    { pathname: "/api/wallet/address", search: "" },
    { pathname: "/api/wallet/address", search: "?rotate=1" },
  ].map((c) => ({ ...c, result: signingPath(c.pathname, c.search) })),
  hashBody: [
    { body: '{"a":1}', result: hashBody('{"a":1}') },
    { body: '{"a":2}', result: hashBody('{"a":2}') },
  ],
  canonical: [
    {
      parts: {
        method: "post",
        path: "/api/wallet/send",
        timestamp: "1",
        nonce: "n",
        bodyHash: "h",
      },
      text: canonicalRequest({
        method: "post",
        path: "/api/wallet/send",
        timestamp: "1",
        nonce: "n",
        bodyHash: "h",
      }).toString("utf8"),
    },
  ],
  nonce: [
    { input: "a1b2c3d4-e5f6-4789-a012-3456789abcde", valid: true },
    { input: "not-a-uuid", valid: false },
    { input: "", valid: false },
  ],
  loopback: [
    { input: "127.0.0.1", expected: true },
    { input: "192.168.1.1", expected: false },
    { input: "LOCALHOST", expected: true },
  ],
  hostHeader: [
    { input: "127.0.0.1:3000", expected: "127.0.0.1" },
    { input: null, expected: null },
  ],
  challengeMsg: [
    {
      challenge: "abc123",
      register: challengeMessage("abc123"),
      setup: webauthnSetupMessage("abc123"),
    },
  ],
  timestamp: [
    { now: NOW, ts: NOW, expected: true },
    { now: NOW, ts: NOW + MAX_CLOCK_SKEW_MS, expected: true },
    { now: NOW, ts: NOW + MAX_CLOCK_SKEW_MS + 1, expected: false },
  ],
  pendingOp: [
    { pathname: "/api/wallet/send", search: "", expected: "send" },
    { pathname: "/api/wallet/send/estimate", search: "", expected: "send" },
    { pathname: "/api/wallet/address", search: "?rotate=1", expected: "rotateAddress" },
    { pathname: "/api/wallet/balance", search: "", expected: null },
  ],
};

const outDir = join(root, "lean", "ArkWallet");
mkdirSync(outDir, { recursive: true });
writeFileSync(join(outDir, "FvFixtures.lean"), emitFixtures(data), "utf8");
console.log(`Wrote ${join(outDir, "FvFixtures.lean")}`);
