#!/usr/bin/env node
/**
 * Extract pure-function fixtures for Lean refinement tests.
 * Writes lean/ArkWallet/FvFixtures.lean
 */
import { mkdirSync, writeFileSync } from "node:fs";
import { join } from "node:path";
import {
  CANONICAL_VERSION,
  canonicalRequest,
  hashBody,
  signingPath,
} from "@/lib/crypto/canonical";
import {
  challengeMessage,
  webauthnSetupMessage,
} from "@/lib/crypto/challenge-messages";
import { isValidNonceUuid } from "@/lib/crypto/nonce-format";
import { MAX_CLOCK_SKEW_MS } from "@/lib/security/constants-base";
import {
  hostFromRequestHeader,
  isLoopbackHostname,
} from "@/lib/security/loopback";
import {
  pendingOpTypeForPath,
  type PendingOpType,
} from "@/lib/webauthn/pending-op-paths";
import { repoRoot } from "./lib/process";

const EXTRACT_SCRIPT = "tsx scripts/fv-extract.ts";
const NOW = 1_700_000_000_000;

function isTimestampValidAt(timestampMs: number, now: number): boolean {
  return Math.abs(now - timestampMs) <= MAX_CLOCK_SKEW_MS;
}

function challengeMessageText(challenge: string): string {
  return new TextDecoder().decode(challengeMessage(challenge));
}

function webauthnSetupMessageText(challenge: string): string {
  return new TextDecoder().decode(webauthnSetupMessage(challenge));
}

/** Lean `PendingOpType` uses camelCase for `rotate-address`. */
function pendingOpToLean(op: PendingOpType | null): string | null {
  if (op === null) return null;
  if (op === "rotate-address") return "rotateAddress";
  return op;
}

function leanStr(s: string): string {
  return JSON.stringify(s);
}

interface FixtureData {
  version: string;
  signingPath: Array<{
    pathname: string;
    search: string;
    result: string;
  }>;
  hashBody: Array<{ body: string; result: string }>;
  canonical: Array<{
    parts: {
      method: string;
      path: string;
      timestamp: string;
      nonce: string;
      bodyHash: string;
    };
    text: string;
  }>;
  nonce: Array<{ input: string; valid: boolean }>;
  loopback: Array<{ input: string; expected: boolean }>;
  hostHeader: Array<{ input: string | null; expected: string | null }>;
  challengeMsg: Array<{
    challenge: string;
    register: string;
    setup: string;
  }>;
  timestamp: Array<{ now: number; ts: number; expected: boolean }>;
  pendingOp: Array<{
    pathname: string;
    search: string;
    expected: string | null;
  }>;
}

function emitFixtures(data: FixtureData): string {
  const lines = [
    "/-!",
    `  AUTO-GENERATED by \`${EXTRACT_SCRIPT}\` — do not edit by hand.`,
    "-/",
    "",
    "namespace ArkWallet.FvFixtures",
    "",
    `def canonicalVersion : String := ${leanStr(data.version)}`,
    "",
  ];

  const emit = (name: string, value: string | boolean): void => {
    if (typeof value === "boolean") {
      lines.push(`def ${name} : Bool := ${value ? "true" : "false"}`);
    } else {
      lines.push(`def ${name} : String := ${leanStr(value)}`);
    }
    lines.push("");
  };

  data.signingPath.forEach((c, i) => {
    emit(`signingPath${i}_pathname`, c.pathname);
    emit(`signingPath${i}_search`, c.search);
    emit(`signingPath${i}_expected`, c.result);
  });

  data.hashBody.forEach((c, i) => {
    emit(`hashBody${i}_input`, c.body);
    emit(`hashBody${i}_expected`, c.result);
  });

  data.canonical.forEach((c, i) => {
    emit(`canonical${i}_method`, c.parts.method);
    emit(`canonical${i}_path`, c.parts.path);
    emit(`canonical${i}_timestamp`, c.parts.timestamp);
    emit(`canonical${i}_nonce`, c.parts.nonce);
    emit(`canonical${i}_bodyHash`, c.parts.bodyHash);
    emit(`canonical${i}_text_expected`, c.text);
  });

  data.nonce.forEach((n, i) => {
    emit(`nonce${i}_input`, n.input);
    lines.push(`def nonce${i}_valid_expected : Bool := ${n.valid ? "true" : "false"}`);
    lines.push("");
  });

  data.loopback.forEach((c, i) => {
    emit(`loopbackHost${i}_input`, c.input);
    lines.push(`def loopbackHost${i}_expected : Bool := ${c.expected ? "true" : "false"}`);
    lines.push("");
  });

  data.hostHeader.forEach((c, i) => {
    if (c.input === null) {
      lines.push(`def hostHeader${i}_input : Option String := none`);
    } else {
      lines.push(`def hostHeader${i}_input : Option String := some ${leanStr(c.input)}`);
    }
    if (c.expected === null) {
      lines.push(`def hostHeader${i}_expected : Option String := none`);
    } else {
      lines.push(`def hostHeader${i}_expected : Option String := some ${leanStr(c.expected)}`);
    }
    lines.push("");
  });

  data.challengeMsg.forEach((c, i) => {
    emit(`challengeMsg${i}_challenge`, c.challenge);
    emit(`challengeMsg${i}_register_expected`, c.register);
    emit(`challengeMsg${i}_setup_expected`, c.setup);
  });

  data.timestamp.forEach((c, i) => {
    lines.push(`def timestamp${i}_now : Nat := ${c.now}`);
    lines.push(`def timestamp${i}_ts : Nat := ${c.ts}`);
    lines.push(`def timestamp${i}_expected : Bool := ${c.expected ? "true" : "false"}`);
    lines.push("");
  });

  data.pendingOp.forEach((c, i) => {
    emit(`pendingOp${i}_pathname`, c.pathname);
    emit(`pendingOp${i}_search`, c.search);
    if (c.expected === null) {
      lines.push(`def pendingOp${i}_expected : Option String := none`);
    } else {
      lines.push(`def pendingOp${i}_expected : Option String := some ${leanStr(c.expected)}`);
    }
    lines.push("");
  });

  lines.push("end ArkWallet.FvFixtures");
  lines.push("");
  return lines.join("\n");
}

const data: FixtureData = {
  version: CANONICAL_VERSION,
  signingPath: [
    { pathname: "/api/wallet/address", search: "?rotate=1&foo=2" },
    { pathname: "/api/wallet/address", search: "?foo=2&rotate=1" },
    { pathname: "/api/wallet/address", search: "" },
    { pathname: "/api/wallet/address", search: "?rotate=1" },
  ].map((c) => ({ ...c, result: signingPath(c.pathname, c.search) })),
  hashBody: [
    { body: '{"a":1}', result: hashBody('{"a":1}') },
    { body: '{"a":2}', result: hashBody('{"a":2}') },
  ],
  canonical: [
    {
      parts: {
        method: "post",
        path: "/api/wallet/send",
        timestamp: "1",
        nonce: "n",
        bodyHash: "h",
      },
      text: new TextDecoder().decode(
        canonicalRequest({
          method: "post",
          path: "/api/wallet/send",
          timestamp: "1",
          nonce: "n",
          bodyHash: "h",
        }),
      ),
    },
  ],
  nonce: [
    {
      input: "a1b2c3d4-e5f6-4789-a012-3456789abcde",
      valid: isValidNonceUuid("a1b2c3d4-e5f6-4789-a012-3456789abcde"),
    },
    { input: "not-a-uuid", valid: isValidNonceUuid("not-a-uuid") },
    { input: "", valid: isValidNonceUuid("") },
  ],
  loopback: [
    { input: "127.0.0.1", expected: isLoopbackHostname("127.0.0.1") },
    { input: "192.168.1.1", expected: isLoopbackHostname("192.168.1.1") },
    { input: "LOCALHOST", expected: isLoopbackHostname("LOCALHOST") },
  ],
  hostHeader: [
    { input: "127.0.0.1:3000", expected: hostFromRequestHeader("127.0.0.1:3000") },
    { input: null, expected: hostFromRequestHeader(null) },
  ],
  challengeMsg: [
    {
      challenge: "abc123",
      register: challengeMessageText("abc123"),
      setup: webauthnSetupMessageText("abc123"),
    },
  ],
  timestamp: [
    { now: NOW, ts: NOW, expected: isTimestampValidAt(NOW, NOW) },
    {
      now: NOW,
      ts: NOW + MAX_CLOCK_SKEW_MS,
      expected: isTimestampValidAt(NOW + MAX_CLOCK_SKEW_MS, NOW),
    },
    {
      now: NOW,
      ts: NOW + MAX_CLOCK_SKEW_MS + 1,
      expected: isTimestampValidAt(NOW + MAX_CLOCK_SKEW_MS + 1, NOW),
    },
  ],
  pendingOp: [
    {
      pathname: "/api/wallet/send",
      search: "",
      expected: pendingOpToLean(pendingOpTypeForPath("/api/wallet/send", "")),
    },
    {
      pathname: "/api/wallet/send/estimate",
      search: "",
      expected: pendingOpToLean(
        pendingOpTypeForPath("/api/wallet/send/estimate", ""),
      ),
    },
    {
      pathname: "/api/wallet/address",
      search: "?rotate=1",
      expected: pendingOpToLean(
        pendingOpTypeForPath("/api/wallet/address", "?rotate=1"),
      ),
    },
    {
      pathname: "/api/wallet/balance",
      search: "",
      expected: pendingOpToLean(pendingOpTypeForPath("/api/wallet/balance", "")),
    },
  ],
};

const root = repoRoot();
const outDir = join(root, "lean", "ArkWallet");
mkdirSync(outDir, { recursive: true });
const outPath = join(outDir, "FvFixtures.lean");
writeFileSync(outPath, emitFixtures(data), "utf8");
console.log(`Wrote ${outPath}`);
